<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.aop-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.asm-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.aspects-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.beans-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.context.support-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.context-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.core-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.expression-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.instrument.tomcat-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.instrument-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.jdbc-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.jms-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.orm-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.oxm-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.test-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.transaction-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.web.portlet-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.web.servlet-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.web.struts-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/spring-framework-3.0.5.RELEASE/spring-framework-3.0.5.RELEASE/src/org.springframework.web-sources-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-bean-validator-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-bindy-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-cache-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-castor-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-cometd-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-context-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-core-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-crypto-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-csv-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-cxf-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-eventadmin-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-freemarker-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-ftp-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-gae-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-guice-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-ibatis-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-jasypt-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-javaspace-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-jaxb-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-jdbc-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-jms-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-josql-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-jxpath-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-mail-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-mina-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-msv-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-saxon-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-script-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-spring-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-spring-javaconfig-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-sql-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-stream-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-stringtemplate-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-tagsoup-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-test-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/camel-xmlbeans-2.7.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/commons-management-1.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/slf4j-api-1.5.11.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/commons-beanutils-1.8.3.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/commons-collections-3.2.1.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/commons-dbcp-1.3.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/commons-lang-2.4.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/commons-pool-1.5.4.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/geronimo-j2ee-jacc_1.0_spec-1.1.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/geronimo-j2ee-management_1.0_spec-1.1.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/geronimo-jms_1.1_spec-1.1.1.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/jasypt-1.7.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/log4j-1.2.16.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/optional/slf4j-log4j12-1.5.11.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/aopalliance-1.0.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/commons-logging-1.1.1.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-aop-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-asm-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-beans-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-context-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-context-support-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-core-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-expression-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-jdbc-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-jms-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-orm-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-test-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-tx-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/apache-camel-2.7.0/lib/spring/spring-web-3.0.5.RELEASE.jar"/>
	<classpathentry kind="lib" path="C:/Documents and Settings/Administrator/My Documents/Downloads/org.apache.servicemix.specs.stax-api-1.0-1.6.0.jar"/>
	<classpathentry kind="lib" path="C:/Documents and Settings/Administrator/My Documents/Downloads/org.apache.servicemix.bundles.commons-csv-1.0-r706899_1.jar"/>
	<classpathentry kind="lib" path="C:/Documents and Settings/Administrator/My Documents/Downloads/org.apache.servicemix.bundles.jaxb-impl-2.1.6_1.jar"/>
	<classpathentry kind="lib" path="C:/Documents and Settings/Administrator/My Documents/Downloads/org.apache.servicemix.specs.jaxb-api-2.1-1.3.0.jar"/>
	<classpathentry kind="lib" path="C:/Documents and Settings/Administrator/My Documents/Downloads/org.apache.servicemix.specs.stax-api-1.0-1.3.0.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
